service: products
frameworkVersion: "3"

plugins:
  - serverless-esbuild

resources:
  Resources:
    ItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "catalogItemsQueue"


provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-west-1
  iam:
    role:
      name: "DynamoDB-Dev-lambdaRole"
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource:
            - "arn:aws:dynamodb:eu-west-1:374052466963:table/products"
            - "arn:aws:dynamodb:eu-west-1:374052466963:table/stocks"

functions:
  getProductsList:
    handler: getProductsList.getProductsList

    events:
      - http:
          method: GET
          path: "/products"
          cors: true
  getProductsById:
    handler: getProductsById.getProductsById
    events:
      - http:
          method: GET
          path: "/products/{id}"
          cors: true
  createProduct:
    handler: createProduct.createProduct
    events:
      - http:
          method: POST
          path: "/products"
          cors: true
  catalogBatchProcess:
    handler: catalogBatchProcess.catalogBatchProcess
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ItemsQueue
              - Arn
          batchSize: 5
